In [1]:
import pandas as pd

In [2]:
import numpy as np
import os

In [3]:
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv(r"C:\Users\user\Downloads\Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
type(dataset)

pandas.core.frame.DataFrame

In [6]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [7]:
dataset.isnull

<bound method DataFrame.isnull of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [8]:
dataset.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [9]:
dataset['Age'].fillna((dataset['Age'].mean()),inplace=True)
dataset['Salary'].fillna((dataset['Salary'].mean()),inplace=True)


In [10]:

dataset['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [11]:
dataset['Age']=dataset['Age'].round()

In [12]:
dataset['Purchased'].value_counts()

No     5
Yes    5
Name: Purchased, dtype: int64

In [13]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [14]:
# separating dependent variables and dependent variables in the dataset

In [15]:
x=dataset.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
y=dataset.iloc[:,-1].values
y



array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [17]:
y.ndim

1

In [18]:
x.ndim

2

In [19]:
x.shape

(10, 3)

In [20]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [21]:
y.shape # output should be(10,1)

(10,)

In [22]:
x #array.....

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Step 5: Encoding Categorical text variables


In [23]:
import sklearn

In [24]:
sklearn.__version__

'0.22.1'

In [25]:
from sklearn.compose import ColumnTransformer

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")

In [33]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [28]:
x= ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="drop")
x= ct.fit_transform(x)
x

In [29]:
x.shape


(10, 5)

Removing dummy variable

In [30]:
x=x[:,1:]
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [31]:
x.shape

(10, 4)

In [35]:
from sklearn.preprocessing import LabelEncoder


In [36]:
lb= LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [37]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-6.54653671e-01, -6.54653671e-01,  7.55609652e-01,
         7.49473254e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.71465267e+00,
        -1.43817841e+00],
       [ 1.52752523e+00, -6.54653671e-01, -1.27872403e+00,
        -8.91265492e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.16247639e-01,
        -2.53200424e-01],
       [ 1.52752523e+00, -6.54653671e-01,  1.74371458e-01,
         6.63219199e-16],
       [-6.54653671e-01, -6.54653671e-01, -5.52176284e-01,
        -5.26656882e-01],
       [-6.54653671e-01,  1.52752523e+00,  2.90619097e-02,
        -1.07356980e+00],
       [-6.54653671e-01, -6.54653671e-01,  1.33684785e+00,
         1.38753832e+00],
       [ 1.52752523e+00, -6.54653671e-01,  1.62746694e+00,
         1.75214693e+00],
       [-6.54653671e-01, -6.54653671e-01, -2.61557187e-01,
         2.93712492e-01]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x

In [ ]:
x_train.shape

In [ ]:
y_train.shape

In [ ]:
x_test

In [ ]:
y_test